/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as ApiGeocodeRouteImport } from './routes/api/geocode'
import { Route as ApiOsmMapRouteImport } from './routes/api/osm-map'
import { Route as ApiOverpassRouteImport } from './routes/api/overpass'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeocodeRoute = ApiGeocodeRouteImport.update({
  id: '/api/geocode',
  path: '/api/geocode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOsmMapRoute = ApiOsmMapRouteImport.update({
  id: '/api/osm-map',
  path: '/api/osm-map',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOverpassRoute = ApiOverpassRouteImport.update({
  id: '/api/overpass',
  path: '/api/overpass',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/api/osm-map': typeof ApiOsmMapRoute
  '/api/overpass': typeof ApiOverpassRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/api/osm-map': typeof ApiOsmMapRoute
  '/api/overpass': typeof ApiOverpassRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/api/osm-map': typeof ApiOsmMapRoute
  '/api/overpass': typeof ApiOverpassRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/api/geocode'
    | '/api/osm-map'
    | '/api/overpass'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale'
    | '/api/geocode'
    | '/api/osm-map'
    | '/api/overpass'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/api/geocode'
    | '/api/osm-map'
    | '/api/overpass'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRoute
  ApiGeocodeRoute: typeof ApiGeocodeRoute
  ApiOsmMapRoute: typeof ApiOsmMapRoute
  ApiOverpassRoute: typeof ApiOverpassRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/geocode': {
      id: '/api/geocode'
      path: '/api/geocode'
      fullPath: '/api/geocode'
      preLoaderRoute: typeof ApiGeocodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/osm-map': {
      id: '/api/osm-map'
      path: '/api/osm-map'
      fullPath: '/api/osm-map'
      preLoaderRoute: typeof ApiOsmMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/overpass': {
      id: '/api/overpass'
      path: '/api/overpass'
      fullPath: '/api/overpass'
      preLoaderRoute: typeof ApiOverpassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRoute,
  ApiGeocodeRoute: ApiGeocodeRoute,
  ApiOsmMapRoute: ApiOsmMapRoute,
  ApiOverpassRoute: ApiOverpassRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
