/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGeocodeRouteImport } from './routes/api/geocode'
import { Route as ApiOsmMapRouteImport } from './routes/api/osm-map'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeocodeRoute = ApiGeocodeRouteImport.update({
  id: '/api/geocode',
  path: '/api/geocode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOsmMapRoute = ApiOsmMapRouteImport.update({
  id: '/api/osm-map',
  path: '/api/osm-map',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/api/osm-map': typeof ApiOsmMapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/api/osm-map': typeof ApiOsmMapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/api/osm-map': typeof ApiOsmMapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/geocode' | '/api/osm-map'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/geocode' | '/api/osm-map'
  id: '__root__' | '/' | '/api/geocode' | '/api/osm-map'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiGeocodeRoute: typeof ApiGeocodeRoute
  ApiOsmMapRoute: typeof ApiOsmMapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/geocode': {
      id: '/api/geocode'
      path: '/api/geocode'
      fullPath: '/api/geocode'
      preLoaderRoute: typeof ApiGeocodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/osm-map': {
      id: '/api/osm-map'
      path: '/api/osm-map'
      fullPath: '/api/osm-map'
      preLoaderRoute: typeof ApiOsmMapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiGeocodeRoute: ApiGeocodeRoute,
  ApiOsmMapRoute: ApiOsmMapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
